import { getApp, getApps, initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";
import { doc, getDoc, getFirestore, increment, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";

const firebaseConfig = { apiKey:"AIzaSyAZ1CS05a7rCubn5AtDvTnh6pATMUN0agI",authDomain:"ptg-sub.firebaseapp.com",projectId:"ptg-sub",storageBucket:"ptg-sub.firebasestorage.app",messagingSenderId:"32845891728",appId:"1:32845891728:web:8d166bcb2ba2eaccb3b015",measurementId:"G-HJYWPVSERF" };
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const db = getFirestore(app);
const loading = document.getElementById("adviceLoading");
const errorBox = document.getElementById("adviceError");
const content = document.getElementById("adviceContent");
const DEFAULT_SALE_NAME = "Đức Lương Sun Group";
const DEFAULT_SALE_PHONE = "0387335227";

function text(value, fallback = "Chưa cập nhật") { const result=String(value??"").trim(); return result||fallback; }
function timestampMs(value){return value?.toMillis?.()||Number(value?.seconds||0)*1000||0}
function dateTime(value){const ms=timestampMs(value);return ms?new Date(ms).toLocaleString("vi-VN",{dateStyle:"short",timeStyle:"short"}):"—"}
function tokenFromUrl(){const path=decodeURIComponent(location.pathname).split("/").filter(Boolean);const value=["t","tu-van"].includes(path[0])?path[1]:new URLSearchParams(location.search).get("id");return /^[A-Za-z0-9_-]{8,80}$/.test(value||"")?value:""}
function setText(id,value){const node=document.getElementById(id);if(node)node.textContent=value}
function salePhone(value){let digits=String(value||"").replace(/\D/g,"");if(digits.startsWith("84")&&digits.length>=11)digits=`0${digits.slice(2)}`;return /^0\d{9,10}$/.test(digits)?digits:DEFAULT_SALE_PHONE}
function showError(message){loading.hidden=true;content.hidden=true;errorBox.hidden=false;setText("adviceErrorText",message)}

function fact(label,value){const item=document.createElement("div");item.className="advice-fact";const span=document.createElement("span");const strong=document.createElement("strong");span.textContent=label;strong.textContent=text(value);item.append(span,strong);return item}
function renderUnit(unit,index){const card=document.createElement("article");card.className=`advice-unit${index===0?" primary":""}`;const head=document.createElement("div");head.className="advice-unit-head";const title=document.createElement("div");const label=document.createElement("span");const code=document.createElement("h3");label.textContent=index===0?"Căn đề xuất chính":`Phương án ${index+1}`;code.textContent=text(unit.code);title.append(label,code);head.appendChild(title);if(index===0){const badge=document.createElement("b");badge.textContent="ƯU TIÊN";head.appendChild(badge)}
  const price=document.createElement("div");price.className="advice-price";const priceLabel=document.createElement("span");const priceValue=document.createElement("strong");priceLabel.textContent="Giá tại thời điểm tạo link";priceValue.textContent=text(unit.totalPrice,"Liên hệ sale cập nhật");price.append(priceLabel,priceValue);
  const upfront=document.createElement("p");upfront.className="advice-upfront";const upfrontLabel=document.createElement("strong");upfrontLabel.textContent="Trả trước: ";upfront.append(upfrontLabel,document.createTextNode(text(unit.upfrontPrice,"Theo phương án thanh toán")));
  const facts=document.createElement("div");facts.className="advice-facts";facts.append(fact("Loại căn",unit.unitType),fact("Diện tích",unit.areaText),fact("Tầng",unit.floor),fact("View",unit.view),fact("Hướng",unit.direction),fact("Phương án",unit.scenario));card.append(head,price,upfront,facts);if(index===0)queueMicrotask(()=>renderPrimaryUnitMaps(unit));return card}

function drawMapRect(ctx,rect,scaleX,scaleY,offsetX=0,offsetY=0,{fill="rgba(255,230,0,.5)",stroke="#e32626",lineWidth=5}={}){if(!rect)return;const x=(rect.x-offsetX)*scaleX;const y=(rect.y-offsetY)*scaleY;const width=Math.max(5,rect.width*scaleX);const height=Math.max(5,rect.height*scaleY);ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;ctx.fillRect(x,y,width,height);ctx.strokeRect(x,y,width,height);return{x,y,width,height}}
function drawUnitBadge(ctx,code,mark){if(!mark)return;const label=text(code,"Căn");ctx.save();ctx.font="800 22px system-ui,sans-serif";const width=Math.min(260,Math.max(105,ctx.measureText(label).width+32));const x=Math.max(8,Math.min(mark.x+mark.width+10,ctx.canvas.width-width-8));const y=Math.max(8,Math.min(mark.y-42,ctx.canvas.height-42));ctx.fillStyle="rgba(5,75,72,.94)";ctx.fillRect(x,y,width,34);ctx.fillStyle="#ffe07b";ctx.fillText(label,x+16,y+24);ctx.restore()}
function loadMapImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src})}
async function renderPrimaryUnitMaps(unit){const visuals=document.getElementById("adviceVisuals");const empty=document.getElementById("adviceMapEmpty");visuals.hidden=true;empty.hidden=true;const map=unit?.map;const allowed=new Set(["phankhupark-map.png","lowrise-map-sharp.jpg","lienke-preview.png"]);if(!map||!allowed.has(map.image)||!map.crop||!map.unitRect){empty.hidden=false;return}try{const image=await loadMapImage(`/${map.image}`);const overview=document.getElementById("adviceOverviewMap");const overviewScale=Math.min(1,1100/image.width);overview.width=Math.max(1,Math.round(image.width*overviewScale));overview.height=Math.max(1,Math.round(image.height*overviewScale));const overviewCtx=overview.getContext("2d");overviewCtx.drawImage(image,0,0,overview.width,overview.height);if(map.towerRect)drawMapRect(overviewCtx,map.towerRect,overview.width/image.width,overview.height/image.height,0,0,{fill:"rgba(255,55,45,.14)",stroke:"#e32626",lineWidth:4});const overviewMark=drawMapRect(overviewCtx,map.unitRect,overview.width/image.width,overview.height/image.height,0,0,{lineWidth:4});drawUnitBadge(overviewCtx,unit.code,overviewMark);
  const crop={x:Math.max(0,map.crop.x),y:Math.max(0,map.crop.y),width:Math.min(map.crop.width,image.width-map.crop.x),height:Math.min(map.crop.height,image.height-map.crop.y)};if(crop.width<=0||crop.height<=0)throw new Error("invalid crop");const detail=document.getElementById("adviceUnitMap");const detailScale=Math.min(1,1200/crop.width);detail.width=Math.max(1,Math.round(crop.width*detailScale));detail.height=Math.max(1,Math.round(crop.height*detailScale));const detailCtx=detail.getContext("2d");detailCtx.drawImage(image,crop.x,crop.y,crop.width,crop.height,0,0,detail.width,detail.height);if(map.towerRect)drawMapRect(detailCtx,map.towerRect,detail.width/crop.width,detail.height/crop.height,crop.x,crop.y,{fill:"rgba(255,55,45,.10)",stroke:"#e32626",lineWidth:4});const detailMark=drawMapRect(detailCtx,map.unitRect,detail.width/crop.width,detail.height/crop.height,crop.x,crop.y,{lineWidth:5});drawUnitBadge(detailCtx,unit.code,detailMark);visuals.hidden=false}catch{empty.hidden=false}}

function render(data){setText("adviceCustomer",text(data.customerAlias,"Khách hàng"));setText("adviceOwner",text(data.ownerName,DEFAULT_SALE_NAME));const phone=salePhone(data.ownerPhone);const ownerPhone=document.getElementById("adviceOwnerPhone");const call=document.getElementById("adviceCall");const zalo=document.getElementById("adviceZalo");if(ownerPhone){ownerPhone.textContent=phone;ownerPhone.href=`tel:${phone}`}if(call)call.href=`tel:${phone}`;if(zalo)zalo.href=`https://zalo.me/${phone}`;setText("adviceMeta",`Tạo lúc ${dateTime(data.createdAt)} · Hết hạn ${dateTime(data.expiresAt)}`);const change=document.getElementById("adviceChange");change.className="advice-change";let title="Thông tin đang còn hiệu lực";let message=text(data.changeMessage,"Thông tin được ghi nhận tại thời điểm tạo link.");if(data.revoked){change.classList.add("danger");title="Link này đã được thu hồi";message="Chỉ chủ link đang đăng nhập mới xem được bản lưu này."}else if(timestampMs(data.expiresAt)<=Date.now()){change.classList.add("danger");title="Link này đã hết hạn";message="Chỉ chủ link đang đăng nhập mới xem được bản lưu này."}else if(data.changeState==="price_changed"){change.classList.add("warning");title="Giá hoặc chính sách đã thay đổi"}else if(data.changeState==="unit_unavailable"){change.classList.add("danger");title="Tình trạng căn cần được kiểm tra lại"}else if(data.changeState==="unchecked"){change.classList.add("warning");title="Đang chờ đối chiếu bảng hàng"}setText("adviceChangeTitle",title);setText("adviceChangeMessage",message);const units=document.getElementById("adviceUnits");units.textContent="";(Array.isArray(data.units)?data.units:[]).slice(0,3).forEach((unit,index)=>units.appendChild(renderUnit(unit,index)));loading.hidden=true;errorBox.hidden=true;content.hidden=false;document.title=`Báo giá · ${text(data.customerAlias,"Khách hàng")} · ${text(data.primaryUnitCode,"Căn đề xuất")} · SUBC`}

async function registerView(id){const key=`ptgsub-advisory-view-${id}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,"1");try{await updateDoc(doc(db,"advisoryLinks",id),{viewCount:increment(1),lastViewedAt:serverTimestamp(),updatedAt:serverTimestamp()})}catch{sessionStorage.removeItem(key)}}

async function start(){const id=tokenFromUrl();if(!id){showError("Đường dẫn tư vấn không hợp lệ.");return}try{const snap=await getDoc(doc(db,"advisoryLinks",id));if(!snap.exists()){showError("Link có thể đã hết hạn hoặc được sale thu hồi.");return}const data=snap.data()||{};render(data);if(!data.revoked&&timestampMs(data.expiresAt)>Date.now())registerView(id)}catch(error){showError(error?.code==="permission-denied"?"Link đã hết hạn, được thu hồi hoặc không còn quyền truy cập.":"Không tải được hồ sơ. Vui lòng kiểm tra kết nối và thử lại.")}}
start();
